// utils/icon-map.ts
import {
  IconCamera,
  IconChartBar,
  IconDashboard,
  IconDatabase,
  IconFileAi,
  IconFileDescription,
  IconFileWord,
  IconFolder,
  IconHelp,
  IconInnerShadowTop,
  IconListDetails,
  IconReport,
  IconSearch,
  IconSettings,
  IconUsers,
  IconBell,
  IconSend,
  IconPuzzle,
  IconHome,
  IconActivity,
  IconTrendingUp,
  IconFilter,
  IconRefresh,
  IconInbox,
  IconRadio,
  IconFileText,
  IconCreditCard,
  IconUsersGroup,
} from "@tabler/icons-react";

export const iconMap = {
  Camera: IconCamera,
  ChartBar: IconChartBar,
  Dashboard: IconDashboard,
  Database: IconDatabase,
  FileAi: IconFileAi,
  FileDescription: IconFileDescription,
  FileWord: IconFileWord,
  Folder: IconFolder,
  Help: IconHelp,
  InnerShadowTop: IconInnerShadowTop,
  ListDetails: IconListDetails,
  Report: IconReport,
  Search: IconSearch,
  Settings: IconSettings,
  Users: IconUsers,
  Bell: IconBell,
  Send: IconSend,
  Puzzle: IconPuzzle,
  Home: IconHome,
  Activity: IconActivity,
  TrendingUp: IconTrendingUp,
  Filter: IconFilter,
  RefreshCw: IconRefresh,
  Inbox: IconInbox,
  Radio: IconRadio,
  FileText: IconFileText,
  CreditCard: IconCreditCard,
  UsersGroup: IconUsersGroup,
};
